---
editor_options:
  markdown:
    wrap: 150
title: "HADDOCK *Melanogrammus aeglefinus*"
format:
  html:
    theme: theme/advice.scss
    fontsize: 1.125em
    linestretch: 1.9
    embed-resources: true
lang: en
crossref:
  fig-title: ''
  #fig-labels: ''
execute:
  echo: false
  warning: false
  message: false
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
source("config.R")
source("quarto_setup.R")
targets::tar_load(c(
  advice_table_landings
))
```

```{r}
#| echo: false
#| output: asis

hr_advice_banner(
  publication_date = publication_date,
  tac = tac,
  tac_last_year = tac_last_year,
  year_end = year_end
)
```

## Advice

MFRI and ICES advise that when the Icelandic management plan is applied, catches in the fishing year `r year_end`/`r year_end+1` should be no more than `r hr_red_dot_number(tac)` tonnes.

## Stock development

Fishing pressure is above HR~MSY~ and HR~pa~ and below HR~lim~; spawning stock size is above MSY B~trigger~, B~pa~ and B~lim~.

```{r}
#| echo: false
ggiraph::girafe(ggobj =
  hr_advice_plot_landings(advice_table_landings, year_end = params$year_end, lang = lang),
  #TODO: + recr('en') + fpl('en') + ssb('en'),
                options = list(
                  #ggiraph::opts_hover_inv(css = "opacity:0.7;"),
                  #ggiraph::opts_hover(css = "stroke-width:2;"),
                  #ggiraph::opts_sizing(width = .7),
                  ggiraph::opts_zoom(max = 5)
                ))
```

```{r}
#| echo: false
#| output: asis

cat(hr_git_revision(as_html = TRUE))
```
